/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
    const { nodes, materials } = useSpline('https://prod.spline.design/OXhxWphgbNEQxnUZ/scene.splinecode')
    return (
        <>
            <color attach="background" args={['#5e6063']} />
            <group {...props} dispose={null}>
                <mesh
                    name="Sphere123"
                    geometry={nodes.Sphere123.geometry}
                    material={materials.Sphere123}
                    castShadow
                    receiveShadow
                />
                <mesh
                    name="Plane123"
                    geometry={nodes.Plane123.geometry}
                    material={materials['Plane123 Material']}
                    castShadow
                    receiveShadow
                    rotation={[-Math.PI / 2, 0, 0]}
                />
                <OrthographicCamera
                    name="1"
                    makeDefault={true}
                    far={100000}
                    near={-100000}
                    position={[-4204.57, 569.3, 4708.23]}
                    rotation={[-0.12, -0.73, -0.08]}
                    scale={1}
                />
                <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
            </group>
        </>
    )
}
